### ISSUE TITLE
Download link refers to Simpe menu releases

### ISSUE THREAD

**Issue by TheDutchJewel** [JustCarmen/webtrees-simple-footer#1]
The download link for the Simple _footer_ module in the [Installation & upgrading section](https://github.com/JustCarmen/webtrees-simple-footer#installation--upgrading), refers to the [Simple _menu_ releases](https://github.com/JustCarmen/webtrees-simple-menu/releases/latest)

**Comment by JustCarmen** [comment]
Thanks. That's what happens if you make a copy of another module...

**Comment by TheDutchJewel** [comment]
Same problem with the issue link in the [Bugs and feature requests](https://justcarmen.nl/modules-webtrees-2/simple-footer/#user-content-bugs-and-feature-requests) section. It refers to the [Simple _menu_ issues](https://github.com/JustCarmen/webtrees-simple-menu/issues?state=open)
